# Generated by Django 2.0.2 on 2018-03-14 07:57

import django.contrib.postgres.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone_num', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('pass_ser', models.CharField(max_length=5, verbose_name='Серия паспорта')),
                ('pass_num', models.CharField(max_length=6, verbose_name='Номер паспорта')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Скоринговый балл')),
            ],
            options={
                'verbose_name': 'Анкета клиента',
                'verbose_name_plural': 'Анкеты клиента',
            },
        ),
    ]
