# Generated by Django 2.0.2 on 2018-03-14 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Создано'),
        ),
    ]
