# Generated by Django 2.0.3 on 2018-03-18 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='owner',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='partners.Organization', verbose_name='Партнёр'),
        ),
    ]
