# Generated by Django 2.0.2 on 2018-03-16 05:43

from django.conf import settings
import django.contrib.postgres.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worksheets', '0001_initial'),
        ('common', '0003_model_offer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=django.contrib.postgres.functions.RandomUUID(), editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('status', models.CharField(choices=[('N', 'Новая'), ('S', 'Отправленная')], default='N', max_length=1, verbose_name='Статус')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Offer', verbose_name='Предложение')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheets.Worksheet', verbose_name='Анкета клиента')),
            ],
            options={
                'verbose_name': 'Заявка в кредитную организацию',
                'verbose_name_plural': 'Заявки в кредитные организации',
            },
        ),
    ]
