# Generated by Django 2.0.2 on 2018-03-13 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_auto_20180313_1023'),
        ('worksheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('status', models.CharField(choices=[('N', 'Новая'), ('S', 'Отправленная')], default='N', max_length=1, verbose_name='Статус')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Offer', verbose_name='Предложение')),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheets.Worksheet', verbose_name='Анкета клиента')),
            ],
            options={
                'verbose_name': 'Заявка в кредитную организацию',
                'verbose_name_plural': 'Заявки в кредитные организации',
            },
        ),
    ]
