# Generated by Django 2.0.2 on 2018-03-13 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Кредитная организация', 'verbose_name_plural': 'Кредитные организации'},
        ),
    ]
