# Generated by Django 2.0.3 on 2018-03-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_add_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='api_access',
            field=models.CharField(blank=True, choices=[('/credits/', 'Кредитное API'), ('/partners/', 'Партнерское API')], max_length=20, null=True, verbose_name='Доступ к API'),
        ),
    ]
